config/routes.rb
Blog::Application.routes.draw do
  
  resources :posts
  root 'static_pages#home'

  match 'home/',  to: 'static_pages#home',            via: 'get'
  match 'contact/',  to: 'static_pages#contact',      via: 'get'
  match 'archive/',  to: 'static_pages#archive',      via: 'get'
  match 'portfolio/',  to: 'static_pages#portfolio',  via: 'get'
  match 'resources/',  to: 'static_pages#resources',  via: 'get'
  match 'about/',  to: 'static_pages#about',          via: 'get'

end

app/models/post.rb
class Post < ActiveRecord::Base
	extend FriendlyId
	friendly_id :title, use: :slugged
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate, :except => [ :show ]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.friendly.find(params[:id])

    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :author)
    end


  def authenticate
    authenticate_or_request_with_http_basic do |name, password|
      name == "andrewhouse" && password == "password"
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end

  def archive
  end

  def portfolio
  end

  def resources
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
	
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Andrew House : "Blog" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="andrew_header">
      <h1><%= link_to "Andrew House", root_path, class: "brand" %></h1>
    </div>
    
    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">

          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <div class="container-fluid nav-collapse">
            <ul class="nav pull-right">
              <li><%= link_to "Home", home_path %></li>
              <li><%= link_to "Resources", resources_path  %></li>
              <li><%= link_to "Portfolio", portfolio_path %></li>
              <li><%= link_to "Contact", contact_path  %></li>
              <li><%= link_to "About", about_path  %></li>


            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span2">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">
                <%= link_to "Archives", archive_path  %>
              </li>
              <% Post.all.each do |posted| %>
                <li><%= link_to posted.title, "/posts/#{posted.slug}" %></li>
                <hr />
              <% end %>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span10">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Andrew House 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Author</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= post.author %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
<div class="show-body">

	<h3><%= @post.title %></h3>


	<h5>Author: <%= @post.author %></h5>

	<p class="home-content">
  	<%= @post.content %>
	</p>
</div>

app/views/static_pages/about.html.erb
<h1>About Me</h1>
<br />
<p>Andrew House, 26 from Kentucky. </p>
<p>I am a self taught Rails enthusiast.</p>

app/views/static_pages/archive.html.erb
<h1>All blog posts</h1>
<div class="home">

	<% Post.all.each do |post| %>
	<div class="home-body">
	<h2><%= link_to post.title, "/posts/#{post.slug}" %></h2>
	<h6><%= post.created_at.strftime("%d %b. %Y") %></h6>
	<p class="home-content"><%= post.content %></p>
	<hr />
</div>
<% end %>
</div>

app/views/static_pages/contact.html.erb
<h1>Contact Me</h1>
<br />
<p>Send me an email to andrewhouse621@gmail.com if you have any questions </p>

app/views/static_pages/home.html.erb
<div class="home">

	<% Post.all.each do |post| %>
	<div class="home-body">
	<h2><%= link_to post.title, "/posts/#{post.slug}" %></h2>
	<h6><%= post.created_at.strftime("%d %b. %Y") %></h6>
	<p class="home-content"><%= post.content %></p>
	<hr />
</div>
<% end %>
</div>

app/views/static_pages/portfolio.html.erb
<h1>My Portfolio</h1>
<br />
<h4><%= link_to "My Blog", root_path %></h4>
	<p>The blog you're currently on was written by me completely from scratch.<p>
		<br />

app/views/static_pages/resources.html.erb
<h1>Helpful Links</h1>
<br />
<h4><%= link_to "Michael Hartl's Rails Tutorial", "http://ruby.railstutorial.org/" %></h4>
	<p>I read the tutorial twice. Once before watching the treehouse rails videoes, and again afterwards. He does a fantastic job explaining how rails works and what to expect when developing rails applications.</p>
	<br />
<h4><%= link_to "Team Treehouse", "http://teamtreehouse.com/" %></h4>
	<p>Subscription is $25 a month, but worth every penny. Has screencast tutorials from beginning HTML and CSS to developing advanced Rails Applications.</p>
  <br />
<h4><%= link_to "Rails Guides", "http://guides.rubyonrails.org/" %></h4>
	<p>Great overview on rails specifics. Gives a clear definition of how MVC is implemented in Rails and how each part's role is distributed.</p>
	<br />
	<br />
<h1>Favorite Gems</h1>
<br />
<h4><%= link_to "Paperclip", "https://github.com/thoughtbot/paperclip" %></h4>
	<p>Paperclip allows the ability to attach files (pictures, documents, etc) and upload them. Easily be able to upload avatars, pre-typed html and many many other uses.</p>
	<br />
<h4><%= link_to "Twitter Bootstrap", "https://github.com/seyhunak/twitter-bootstrap-rails" %></h4>
	<p>Easy implementation of start up CSS. I find myself lacking in the design department and Bootstrap gives me a great start on designing a website.</p>
	<br />
<h4><%= link_to "Devise", "https://github.com/plataformatec/devise" %></h4>
	<p>Want users to be able to log in to your website and perform tasks specific to them? Devise is perfect for that. It comes with several helpers that make doing user specific tasks easy.</p>
	<br />
<h4><%= link_to "Friendly Id", "https://github.com/norman/friendly_id" %></h4>
	<p>Do you hate having a url thats ends with a number id? Friendly Id allows you to be able to use attributes as url names (hooray!).</p>
	<br />  